### ISSUE TITLE
[Not an Issue] just comment

### ISSUE THREAD

**Issue by dhiamonkey** [henriquefm/keplerslaws#1]
Man, this stuff you build is really cool.

I wonder if I can make this in react/NextJS

Anyways, Well done Henrique

**Comment by henriquefm** [comment]
Thank you very much! 
I don't know how much you know about react/NextJS, but I bet you can make it even if you are just starting to learn it. This type of project is great to learn a new framework. And it uses Angular only to create the page structure and menu. The actual animation is done with D3.js.

**Comment by dhiamonkey** [comment]
My knowledge in react/NextJS is not that much, but I'm trying to recreate it in React.

Anywho, thank you for the response, Henrique. Hope you're doing well!
